### ISSUE TITLE
21페이지 텐서 합에서 오타가 있습니다.

### ISSUE THREAD

**Issue by jihwanahn** [Justin-A/DeepLearning101#1]
sum_tensor = tensor1 + tensor2
print(sum_tensor)
tensor([[[10., 12.],
         [14., 16.]],
        [[18., 20.],
         [22., 24.]]])

으로 수정되어야 할거 같습니다.

**Comment by Justin-A** [comment]
안녕하세요.

21페이지에 있는 코드에 대한 결과는 다음과 같습니다.

```python
sum_tensor = tensor1 + tensor2
print(sum_tensor)

tensor([[[10., 12.],
         [14., 16.]],

        [[18., 20.],
         [22., 24.]]])
```

지적해주셔서 감사합니다.
