### ISSUE TITLE
p92 개념 수식 재확인 부탁해요.

### ISSUE THREAD

**Issue by joonheepy** [Justin-A/DeepLearning101#10]
안녕하세요

오타 및 오개념으로 인해 고생하며 책 공부하고 있는 독자입니다. 
책 내용구성은 가능한한 많은 내용을 두루 담으려고 노력하신것 같아 좋은데, 
오타가 너무 많고, 특히, 오개념은 학습도중 발목을 잡습니다.. ㅠ

92쪽에 LeCun Uniform Initialization 식이 He Initialization 부분에 씌여져 있네요.. 
모르고 지나쳤더라면 마치 He 수식인걸로 착각했을 것 같습니다... 

그리고 He initialization 수식은 없네요. (일부러 안적으신건지..)
실전에서 적용시 문제가 되는 레이어에서의 input 값들의 분포가 어떠한 양상을 띠고, 활성화 함수가 무엇이냐에 따라 초기화 조건이 달라져야 하는데 그래서 초기화 관련 수식은 반드시 있어야 한다고 생각합니다. loss값 감소가 더디거나 진행에 문제가 있을 때 문제되는 레이어에서 input 값의 분포를 보고 어떤 초기화 방법을 사용할지 결정하게 되기 때문입니다. 

그리고 He Initialization의 경우 독자가 "그래서 He Initialization이 무엇인가요?"하고 물었을 때 책에 있는 내용은 제대로 된 설명이 되지 못하는 것 같습니다. ReLU 활성화 함수 사용시 Xavier가 최종 결과값을 0으로 만들어버리는 단점을 극복하기 위해 He 초기화를 사용한다고 하였는데, 그래서 He가 어떤 초기화 방법인지에 대한것인지는 안적어주셨어요. 설명해주셨으면 더 좋았을것 같습니다. 

또한 Initialization 관련하여 Glorot Initialization은 가장 많이 사용되는 초기화 방법중의 하나인데 하필 이 부분만 책에서 쏙 빼 놓은 점도 약간 의아스럽습니다.... 

아무튼 수식관련 내용은 수정 부탁드립니다. 
감사합니다.

**Comment by Justin-A** [comment]
안녕하세요, Justin입니다.

우선, 책에 대해 문제가 많은 부분 굉장히 죄송스럽게 생각하고 있습니다.
저장소 README에 작성된 만큼, 편집 과정에서 오타가 많이 발생하였으며 편집 오류로 인해 많은 혼란이 일어나는 것 같습니다.

우선, 문의해주신 내용은, He Initialization 부분에 작성된 수식은 LeCun Uniform Initialization 부분에 작성되어야 하는 것이 맞습니다. 또한, 이 책은 초보자를 대상으로 작성된 책이기 때문에, weight initialization 에 대해서는 깊게 다루지 않았습니다. 이와 관련된 내용은 구글링 혹은 관련 문헌의 내용을 참고하여서 공부하시는 걸 추천합니다.

현재 책의 수식과 오타에 대한 수정은 1~2월에 인쇄될 2판에 최대한 반영하려고 저자들과 같이 노력하고 있습니다. 하지만 책의 출판의 특성상 2판 인쇄 때, 추가적인 내용이 들어가긴 어렵다고 하며 현재 작성된 내용을 바탕으로 많은 수정 및 개선이 진행 될 것이라 예상됩니다. 참고 부탁드립니다.

감사합니다.
