### ISSUE TITLE
Chapter 6 제보

### ISSUE THREAD

**Issue by ckdehd200** [Justin-A/DeepLearning101#11]
오타.
p.274 minimax식 이후 : '경찰'의 입장에서는 D(x)가 1이고(진짜 데이터를 1로 구분) 'D(G(z))'가 0일때
-> 위의 문장에서 따옴표 안의 단어들이 빠져있습니다. 

수정 제안.
p.282 : 그런데 (1,1)에서 왼쪽으로 '또는' 위로 가는 Action은
 '또는'이라는 단어를 넣어주는 것이 읽을 때 매끄럽다고 생각됩니다.

**Comment by Justin-A** [comment]
안녕하세요, Justin입니다.

p.274 내용의 경우, 통일성을 위해 '경찰'의 입장보다는 'D'의 입장으로 표현하는게 좋을 것 같습니다. 또한, 'D(G(z))'가 0일 때로 수정되어야 될 것 같습니다.

p.282 내용의 경우, '또는' 이 추가되어야 자연스럽게 표현될 것 같습니다.

지적해주셔서 감사드립니다.
