### ISSUE TITLE
(p.63) PART 02 예제 2-1의 '5. 데이터 확인하기' 부분 문의 드립니다.

### ISSUE THREAD

**Issue by Philip-Kim** [Justin-A/DeepLearning101#12]
안녕하세요.
딥러닝에 관심은 있었는데 어디부터 시작해야될지 몰라서 고민하던 차에 이 책을 구입하게 되었습니다.
수학, 통계와는 거리가 먼 전공이라 많이 어렵지만 그래도 이 책 덕분에 한걸음씩 배울 수 있어 감사 드립니다.

제가 드릴 질문은 63페이지에 있는, 사람의 손글씨 데이터를 이용한 예제의 설명 부분인데요,
페이지 윗부분의 코드인 '5. 데이터 확인하기' 에 대한 설명이 보이질 않습니다.

해당 코드 아래부분의 설명인
//
다운로드한 후 Mini-batch...
(중략)
...torch.LongTensor 형태라는 것도 확인할 수 있습니다.
//
내용은 62페이지 하단의 '4. 데이터 확인하기'의 설명과 동일합니다.

제 생각입니다만, 편집 과정 중 해당 부분이 중복으로 실리고,
원래의 '5. 데이터 확인하기'에 대한 설명이 누락된 것으로 추정됩니다.

이 책의 장점 중 하나가 처음보는 라이브러리나 함수에 대해서도 해당 예제를 이해하는데는 무리없을 정도로 설명이 되어 있다는 점 인데요,
오늘 해당 부분을 읽다보니 해당 부분의 설명이 없어 글을 쓰게 되었네요.

항상 건강하시고, 좋은 하루 되시길 바랍니다.

Philip Kim 드림.

**Comment by Justin-A** [comment]
안녕하세요, Justin입니다.

지적해주신 내용을 확인해 본 결과, '5. 데이터 확인하기' 의 설명 부분이 빠져있네요.
해당되는 내용은 다음과 같습니다.

- 데이터가 실제로 어떻게 생겼는지 사람의 눈으로 직접 확인할 수 있도록 시각화하는 코드입니다.
- [Mini-Batch, Channel, Height, Width]의 형태, 즉 1개의 Mini-Batch 내에는 32개의 데이터가 있으며, 채널이 1개이며, 세로가 28, 가로가 28인 이미지 데이터를 의미하는 [32, 1,28, 28] 데이터 모양 에 대하여, 사람의 눈으로 직접 확인할 수 있도록,  이미지 데이터를 시각화하기 위해 [Width, Height, Channel] 형태로 변환하기 위해 [28, 28, 1] 로 각각 변환하여 시각화를 진행합니다. 
- 제시된 10개의 이미지 데이터 각각은 28 * 28 * 1 개의 픽셀로 구성되어 있는 이미지이며 각 이미지별로 할당된 label 값 역시 올바르게 매칭되어 있는 것을 확인할 수 있습니다.

지적해주셔서 감사합니다.
해당되는 내용은 추후 반영하도록 하겠습니다.
