### ISSUE TITLE
Transfer Learning 예제 오류

### ISSUE THREAD

**Issue by lummsklr** [Justin-A/DeepLearning101#13]
안녕하세요. 책 잘 보고 있습니다.
Google Colab으로 예제 코드들을 돌려보고 있는데, transfer learning 예제에서 오류가 뜹니다(직접 일일이 복붙을 했는데도 불구하고).
cuda()를 처음 사용하는 시점, model = models.resnet18(pretrained = False).cuda(), 에서
CUDA error: device-side assert triggered
라는 오류가 뜹니다.
어떻게 해결해야 하나요?
감사합니다.

**Comment by Justin-A** [comment]
안녕하세요, Justin입니다.

해당되는 내용은 보통 GPU에 모델을 올려줄 때, 메모리 부족으로 인해 발생되는 문제로 많이 확인됩니다.
이러한 경우, 보통 배치 사이즈를 줄여서 문제를 해결할 수 있습니다.
관련된 내용을 구글링을 통해 추가적으로 정보를 확인해보는 것도 도움이 될 것 같습니다.

감사합니다.
