### ISSUE TITLE
PART 04 컴퓨터비전 p.182~p.185 Transfer Learning 실습 중 오류 질문

### ISSUE THREAD

**Issue by aqntks** [Justin-A/DeepLearning101#15]
안녕하세요 파이썬 딥러닝 파이토치 책을 구매해서 공부 중인 학생입니다
''' 10. 미리 학습되지 않은 ResNet18 학습 실행하며 Train, Test set의 Loss 및 Test set Accuracy 확인하기 '''
''' 11. IMAGENET 데이터로 미리 학습이 된 ResNet18 모델을 불러온 후 개미, 벌 이미지 데이터에 맞게 Fine Tuning 해보기 '''
실행 중에 IndexError: Target 2 is out of bounds. 오류가 발생했는데 원인이 무엇인지 모르겠어서 질문 드립니다.
CPU 환경이라 model.cuda() 구문을 model.to(DEVICE)로 바꾼 것 말고는 예제 코드를 수정 한 게 없는데 어떤 이유인가요...

![오류 업](https://user-images.githubusercontent.com/42826598/107141850-dcffc200-696e-11eb-87c4-1c3cbd34a67a.png)
![오류](https://user-images.githubusercontent.com/42826598/107141858-df621c00-696e-11eb-8d61-a8a0d9f7409c.png)

**Comment by Justin-A** [comment]
안녕하세요, Justin입니다.

loss를 계산할 때 이용되는 output, label 간 벡터 크기가 달라서 발생하는 오류로 예상됩니다.
train을 정의할 때, output, label의 shape을 통일해주셔야 둘의 loss값을 계산할 수 있습니다.

**Comment by GyuhyeonHan** [comment]
저도 동일 오류가 떴었는데 해결했습니다.
Kaggle에 올라와있는 자료 자체가 바뀐 거 같아요. 기존에는 Class 0-1까지였는데 오늘(21년 3월 12일) 기준으로 Class가 0-2까지 돼 있었습니다. 저자님의 말씀처럼 벡터 크기를 맞춰주기 위해 8번 코드에서
model.fc = nn.Linear(num_ftrs, 2) 부분을
model.fc = nn.Linear(num_ftrs, 3)으로 수정해주니 잘 작동하네요.

그런데 label이 3종류로 늘어서 그런지, 정답률은 나빠지네요. 데이터셋 자체가 바뀌어서 그런거 같습니다..

**Comment by kimdw92** [comment]
제가 확인해보니, 클래스는 ant랑 bee 2가지가 있는게 맞구요, imageFolder함수 사용할때 아래처럼 경로를 바꿔주었고 (+x 추가) 그리고 hymenoptera_data 폴더 안에는 train과 val 폴더 2가지만 남겨두고 나머지는 삭제했습니다

image_datasets = {x: datasets.ImageFolder("../data/hymenoptera_data/"+x, data_transforms[x]) for x in ['train', 'val']}
