### ISSUE TITLE
5-3_model_imdb_glove.ipynb 파일 keyerror

### ISSUE THREAD

**Issue by fmirazu** [Justin-A/DeepLearning101#17]
안녕하세요. 파이썬 딥러닝 파이토치로 딥러닝 학습중인 직장인입니다.

5-3_model_imdb_glove.ipynb 진행 중에.. 아래와 같이 KeyError 가 발생하는데,
내용상으로는 TEXT.vocab 에 없는 단어에서 발생하는 것으로 추측됩니다.

그런데, OOV가 있는 경우에도 unk_token='[UNK]' 으로 입력되어, Error가
발생하지 않게 되어 있지 않나요? 어떻게 오류를 해결할 수 있을까요?

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-90-e1768833f3b6> in <module>
      1 # Check batch data
----> 2 sample_for_check = next(iter(valid_iterator))
      3 print(sample_for_check)
      4 print(sample_for_check.text)
      5 print(sample_for_check.label)

D:\Anaconda\envs\py38_pytorch\lib\site-packages\torchtext\legacy\data\iterator.py in __iter__(self)
    158                     else:
    159                         minibatch.sort(key=self.sort_key, reverse=True)
--> 160                 yield Batch(minibatch, self.dataset, self.device)
    161             if not self.repeat:
    162                 return

D:\Anaconda\envs\py38_pytorch\lib\site-packages\torchtext\legacy\data\batch.py in __init__(self, data, dataset, device)
     32                 if field is not None:
     33                     batch = [getattr(x, name) for x in data]
---> 34                     setattr(self, name, field.process(batch, device=device))
     35 
     36     @classmethod

D:\Anaconda\envs\py38_pytorch\lib\site-packages\torchtext\legacy\data\field.py in process(self, batch, device)
    229         """
    230         padded = self.pad(batch)
--> 231         tensor = self.numericalize(padded, device=device)
    232         return tensor
    233 

D:\Anaconda\envs\py38_pytorch\lib\site-packages\torchtext\legacy\data\field.py in numericalize(self, arr, device)
    328         if self.use_vocab:
    329             if self.sequential:
--> 330                 arr = [[self.vocab.stoi[x] for x in ex] for ex in arr]
    331             else:
    332                 arr = [self.vocab.stoi[x] for x in arr]

D:\Anaconda\envs\py38_pytorch\lib\site-packages\torchtext\legacy\data\field.py in <listcomp>(.0)
    328         if self.use_vocab:
    329             if self.sequential:
--> 330                 arr = [[self.vocab.stoi[x] for x in ex] for ex in arr]
    331             else:
    332                 arr = [self.vocab.stoi[x] for x in arr]

D:\Anaconda\envs\py38_pytorch\lib\site-packages\torchtext\legacy\data\field.py in <listcomp>(.0)
    328         if self.use_vocab:
    329             if self.sequential:
--> 330                 arr = [[self.vocab.stoi[x] for x in ex] for ex in arr]
    331             else:
    332                 arr = [self.vocab.stoi[x] for x in arr]

KeyError: 'rauol'

**Comment by 8a496b** [comment]
@fmirazu
안녕하세요! 직장일 하시면서 공부라니 고생 많으십니다 ㅠㅠ (저도 해보니까 진짜 힘든 일이더라구요)

말씀하신 에러는 일단은 제가 코드 작성했을 때 사용했던 library(torchtext)와 최신 버전이 달라지면서 나타나는 문제로 파악됩니다. 
관련 이슈로 #9 여기에 작성해둔 것이 있습니다. 제가 달아놓은 내용대로 코드를 최신화 해뒀어야 하는데 늦어졌네요. 
우선 급한 문제라면, 작성 내용대로 버전을 다운그레이드하여 실행시켜보시면 어떨까요? 
최대한 빠른 시일내에 수정해보겠습니다! 

불편을 드려 죄송합니다.
