### ISSUE TITLE
코드 오류 

### ISSUE THREAD

**Issue by nakyolee** [Justin-A/DeepLearning101#19]
안녕하세요 책구매하였고 클래스 수업도 잘 듣고 있습니다. 

5-2_model_imdb_scratch  파일 코드에서 몇가지 문의사항있습니다. 

1. 우선 torchtext 로 imdb 파일을 부르는게 잘 안되더라고요. legacy 를 넣어서 해결해야 하는건가요? legacy 를 넣어서 해보니까 잘 돌아가긴 합니다만, 
2. sample_for_check =next(iter(train_iterator)) 이 부분에 대한 문의입니다. 
data.BucketIterator.splits 이후에 저 코드를 돌려보니 에러가 뜨거든요. next 가 안되는 것 같긴한데...

**Comment by Justin-A** [comment]
@8a496b

**Comment by 8a496b** [comment]
@nakyolee
안녕하세요 답이 많이 늦어서 죄송합니다. torchtext의 버전이 바뀌면서 data 부분이 많이 바뀌었습니다. 
그래서 당장의 해결책은 
- (이미 말씀해주신대로) legaxy를 이용한 코드 수정
- torchtext 버전 다운그레이드
2가지라고 볼 수 있습니다.

새로운 버전의 torchtext에 대응하는 코드 작업은 하고 있으나, 회사 업무나 다른 개인 사정으로 늦어지고 있습니다. 양해 부탁드리겠습니다.
급하시다면 우선 위 두가지 방식 중 한가지를 선택해 해결하시길 권장드립니다. 

늦은 확인에 대해 다시 한 번 사과의 말씀드립니다.
