### ISSUE TITLE
저자분께 질문있습니다.

### ISSUE THREAD

**Issue by shin285** [Justin-A/DeepLearning101#21]
혹시 https://wingnim.tistory.com/34 블로그를 운영하시는 분이 맞으신가요?
그렇다면 해당 블로그에도 아래 이슈에서 보완된 내용으로 수정되어야 할 것 같습니다.

https://github.com/Justin-A/DeepLearning101/issues/16

**Comment by Justin-A** [comment]
안녕하세요, 해당 블로그는 저희 저자와 관련이 없는 블로그입니다.
블로그 관리자에게 문의하면 좋을 것  같습니다!

감사합니다.
