### ISSUE TITLE
파이토치 - cuda 관련 문의사항

### ISSUE THREAD

**Issue by HyunJJon** [Justin-A/DeepLearning101#22]
안녕하십니까 해당 교제 구매 후, 공부하고 있는 학생입니다.
cuda 11.2버전을 설치 후 파이토치 설치 과정에서 cuda 버전을 10.2와 11.3 중에 고르게 되어있어 11.3버전으로 체크 후 설치를 진행하였습니다. ( cudnn은 cuda 11.5와 10.2 중에 고르라고 되어있어 같은 11.x라고 판단되는 11.5를 다운 받았습니다.)
이렇게 설치 후 torch.cuda.is._available('cuda')를 통해 확인 해본 결과 False가 출력되어 제대로 호환이 안됨을 알게되었습니다.

이같은 경우에 3개가 다 같은 버전인 10.2로 맞추어 설치를 진행해야 하나요? 감사합니다.

**Comment by HyunJJon** [comment]
안녕하십니까 해당 교제 구매 후, 공부하고 있는 학생입니다. 
cuda 11.2버전을 설치 후  파이토치 설치 과정에서 cuda 버전을 10.2와 11.3 중에 고르게 되어있어 11.3버전으로 체크 후 설치를 진행하였습니다. ( cudnn은 cuda 11.5와 10.2 중에 고르라고 되어있어 같은 11.x라고 판단되는 11.5를 다운 받았습니다.) 
이렇게 설치 후 torch.cuda.is._available('cuda')를 통해 확인 해본 결과 False가 출력되어 제대로 호환이 안됨을 알게되었습니다.

이같은 경우에 3개가 다 같은 버전인 10.2로 맞추어 설치를 진행해야 하나요? 감사합니다.

**Comment by HyunJJon** [comment]
11.3 버전으로 cuda cudnn 파이토치를 맞추어서 재설치 해보았지만 호환성문제인지 계속 cpu를 사용하는데 해결방안이 있을까요..?

**Comment by Justin-A** [comment]
안녕하세요, 답변드립니다.

PyTorch, CUDA, CuDNN 3가지의 버전이 호환에 맞게 설치하셔야 GPU를 정상적으로 사용할 수 있습니다.
교재에 이용된 라이브러리의 버전은 PyTorch 1.6, CUDA 10.1, 이며 이에 해당되는 CuDNN을 설치하였습니다.

CUDA 11.3 버전으로 이용하실 경우,  이에 맞는 CuDNN을 설치하셔야 하며, 호환성 문제인 경우 처음부터 재설치하시는 것을 추천드립니다. 
일반적으로 개발 환경 셋팅이 제일 오래 걸리며, 구글링을 통해 다양한 정보를 취득하셔서 문제를 해결하시길 기원합니다.
새해 복 많이 받으세요. 감사합니다.
