### ISSUE TITLE
ImportError: Matplotlib requires pyparsing>=2.2.1; you have 2.2.0 ???

### ISSUE THREAD

**Issue by sangjinhong** [Justin-A/DeepLearning101#24]
아래 에러가 뜨는데 어떻게 해야죠???

ImportError: Matplotlib requires pyparsing>=2.2.1; you have 2.2.0

**Comment by Justin-A** [comment]
안녕하세요, 현재 설치된 pyparsing 버전이 낮아서 발생하는 문제로 판단됩니다.
pyparsing을 삭제 및 재설치하시고, 버전이 2.2.1 이상인지 확인하시면 됩니다.
