### ISSUE TITLE
AttributeError: module 'torchtext.data' has no attribute 'Field'

### ISSUE THREAD

**Issue by rovi1202** [Justin-A/DeepLearning101#25]
267쪽에 #(1)을 실행시키면 위 제목과 같은 에러가 납니다. torchtext버전 문제라고 하는데, torch버전도 맞추어야 한다고 합니다.  웹에 있는 방법들도 잘 안돼서 ... 부탁합니다.

**Comment by Justin-A** [comment]
안녕하세요, torch 1.7.0, torchtext 0.3.1 으로 버전을 세팅하시면 올바르게 작동될 것으로 예상됩니다.
관련된 이슈 첨부드립니다. #9 
감사합니다.
