### ISSUE TITLE
안녕하세요. 파이썬 딥러닝 파이토치 책구매자입니다.

### ISSUE THREAD

**Issue by yunholeeme** [Justin-A/DeepLearning101#3]
안녕하세요.

책 잘 보고 있습니다.
그런데 오타와 중복된 부분이 아주 많아요.

오타제보는 여기에 사면되네요?

그런데 정말로 오타가 많아서 다 나열하기 어려울 정도 입니다.

감사합니다.

**Comment by Justin-A** [comment]
안녕하세요, Justin입니다.
책 내용 내 오타 및 중복된 내용이 많아서 죄송합니다. 이슈에 남겨주시면, 내용 확인해서 다음 인쇄때 반영하도록 하겠습니다.
감사합니다.
