### ISSUE TITLE
오타 제보 - PART 03, Deep Learning

### ISSUE THREAD

**Issue by hschoi0705** [Justin-A/DeepLearning101#4]
알찬 구성으로 어려운 내용을 조금이나마 쉽게 설명하기 위해 노력하셨다는 느낌이 많이 드는 책입니다. 특히 코드 한 줄 마다 주석과 설명을 해주어 많은 도움이 될 것 같습니다. 다만 오타나 문맥이 이상한 곳이 많은 것 같습니다. 읽는중 오타나 이상한 부분이 있다면 issues에 남기도록 하겠습니다. 

### 1.  코드 
  - 예제 코드 전반에서 "**콜론( : )**" 누락된 곳이 많습니다. 특히 if, for, def, class 등에서 거의 콜론이 누락되어 있습니다.  Python을 해본 사람은 당연히 알아서 잘 처리하겠지만 Python을 처음 하는 사람이라면 예제코드를 입력하다가 당황할지도 모르겠네요. 
  - 예제3-1, Dropout 적용시 p.82에서는 30%를 적용한다고 언급하고, p.83에서 50%를 적용한다고 언급하며 실제 50%를 적용하였습니다. 일관성을 위해 p.82의 30%를 50%를 변경하여야 할 것으로 보입니다

### 2. 내용
  - p.80, 2번째문단 2째줄, 일반적인 신경망 구조 내용이 중복해서 언급된 것으로 보입니다. 
  - p.80, 3번째문단 2째줄, "Dropout한 것인지" --> "Dropout할 것인지" 가 더 적절해 보입니다. 
  - p.89, 2번째문단 1째줄, [그림3-7] --> [그림3-9] 가 맞을것 같음
  - p.96, RMSProp 설명 2째줄, "\~학습이 오래 진행될수록 부분이 계속 증가해\~", 내용이 누락된 것 같음
  - p.99, 4.7 Stacked AutoEncoder 설명부분에서 [그림 3-17] 은 FashionMNIST 데이터 출력입니다.  [그림 3-15]가 맞을 것 같음
  - p.104 이후, MNIST와 FashionMNIST 혼합되어 사용되고 있음.

**Comment by leeyunhome** [comment]
저와 비슷한 생각을 하시네요. 책 구성이 좋아보이는데, 오타가 많아서 읽기 어려울 때가 있습니다.
정보 공유 감사합니다.

**Comment by Justin-A** [comment]
안녕하세요, Justin입니다.
책 내용을 확인해본 결과, 예제 코드 내 콜론이 누락된 곳이 많네요, 편집 과정 중 문제가 발생된 것 같습니다. 
우선, 본 저장소에 게시되어있는 코드들로 예제 내용을 확인해주시면 감사하겠습니다.
출판사 측과 협의하여 수정하도록 하겠습니다. 죄송합니다. 

그 외 내용들은 저자들과 협의하여 수정하도록 하겠습니다. 감사합니다.

**Comment by Justin-A** [comment]
안녕하세요, Justin입니다.
우선, 현재 올려주신 내용에 대해 답변드립니다.

1. 코드
- 코드 내용 중 콜론이 누락된 곳이 많습니다. 이에 대한 내용은 저장소에 올라온 코드를 참조해주시면 감사하겠습니다. 정오표를 바탕으로 2판 인쇄시 반영하여 수정하도록 하겠습니다. 죄송합니다.
- p.82의 30%를 50%로 변경해야하는 것이 맞습니다. 지적 감사합니다.

2. 내용
- [그림 3-3]은 일반적인 신경망 구조와, Dropout이 적용된 신경망의 구조를 비교한 것입니다. 로 수정되어야 합니다. 
- 'Dropout 기법을 적용할 것인지' 로 수정되어야 합니다.
- 이전 내용을 파악하였을 때, [그림 3-7, 3-8] 내용이 누락되었습니다. p.89에 있는 그림은 3-7이 알맞으며, 2번째 문단의 내용들은 p.89 아래 부분에 있는 내용을 참고하는 것이 맞습니다.
- RMSProp 부분에서, 'Adagrad의 단점은 학습이 오래 진행될수록 G_t 부분이 계속 증가해 Step Size가 작아진다는 것인데~' 로 수정되어야 합니다.
- 참조해야 될 그림은 [그림 3-15]가 맞습니다. [그림 3-17]이 [그림 3-15]로 수정되어야 합니다.
- [예제 3-6]은 FashionMNIST 데이터에 대해서 다루고 있는 내용입니다. 해당 예제 내 MNIST라고 표기된 내용은 모두 FashionMNIST로 수정되어야 합니다.

해당 내용을 반영하여 추후 인쇄 때 수정되도록 참고하겠습니다. 다시 한번 감사드립니다.

**Comment by joonheepy** [comment]
74쪽 분류모형 표 값 정정해주세요.
