### ISSUE TITLE
학습한 모델 저장하고 다른 프로그램에 사용하기

### ISSUE THREAD

**Issue by jih3508** [Justin-A/DeepLearning101#5]
기존 학습하고 난 모델은 pth파일로 저장 한 다음 다른 프로그램에 불러와서 학습된 데이터를 잘 돌아가는지 확인 하고 싶은데,
다을 프로그램에서 초기 모델 설정한 클래스가 있어서 돌릴수 있다고 하는데 혹시 초기 네트워크 없는 상태에서 학습된 모델을 사용하는 방법이 있습니까?

**Comment by 8a496b** [comment]
@jih3508 (cc. @Justin-A @LeeGyeongTak )

안녕하세요! 
질문의 내용과 용어가 약간 혼란스러워서 제가 임의로 해석한바로 설명 드리겠습니다. 원하시는 바가 `a.py`라는 파일에서 학습한 `model_a.pt`라는 모델을 `b.py`라는 파일에서 그대로 불러와서 사용하고 싶으시단 말씀이실까요?

pytorch에서의 모델 저장과 불러오기는 모델 클래스를 선언한 뒤, 각 layer의 학습된 weight를 채워넣어 사용하는 방식을 사용합니다. 즉, 다른 파일 (`b.py`)에서 `model_a.pt`를 사용하고자 하신다면, `model_a.pt`를 저장했던 `a.py` 속 모델 클래스 코드를 `b.py`에도 그대로 가져와서 선언하고, 불러오기를 하셔야 합니다. 아래 공식문서를 확인하시면 더 자세하게 살펴보실 수 있습니다!

https://tutorials.pytorch.kr/beginner/saving_loading_models.html
