### ISSUE TITLE
74-75페이지 오타 확인해주세요 

### ISSUE THREAD

**Issue by joonheepy** [Justin-A/DeepLearning101#7]
74쪽 분류모형 표 값 정정해주세요.

TN FP FN TP 내용은 기본적으로 다른 책에서도 다 다루는 내용인데 이런 부분에서 실수는 없어야 합니다.... ㅠㅠㅠ
처음 하는 사람들은 이런 오타때문에 몇 시간 헤맬수도 있어요 ㅠㅠ

그리고 75페이지도 정상적으로 된 것인가요? 

정밀도(Precision) 부분에 분자는 TP로 되어있는데 설명은 옳게 분류된 불량 데이서 수라고 나와서요... 

블로그나 다른 사이트 찾아보면 반대로 설명되어있는것 같기도 하고.. 

헷갈립니다. 

74-75페이지 전체적으로 확인 부탁드립니다. 

+ 추가: 
75페이지 계속 보다보니 F1 Measure 영어단어도 오타 있네요; ;; 
흠... draft 쓰고 오타 검토는 제대로 하신건가요..? 한 페이지에서 이렇게 많이.. ㅠ 
그 밑에 수식에도 오타있고요.... 참.. 
공부하다가 짜증이 밀려옵니다 ㅠㅠ 아..

**Comment by Justin-A** [comment]
안녕하세요, Justin입니다.
p.74, 75쪽 관련 내용을 살펴보았으며, 정정되어야 할 내용을 공지드립니다.
불편을 드려 죄송합니다.

p.74 [표 2-1] 실제 클래스, 예측된 클래스 기준 
[실제: 정상 / 예측: 정상: True Positive (TP)]
[실제: 정상 / 예측: 불량: False Positive (FP)]
[실제: 불량 / 예측: 정상: False Negative (FN)]
[실제: 불량 / 예측: 불량: True Negative (TN)]

p.75
정밀도(Precision) : (TP) / (TP + FP) : 정상으로 올바르게 예측된 데이터 / 정상으로 예측된 데이터
재현율(Recall) : (TP) / (TP + FN) : 정상으로 올바르게 예측된 데이터 / 실제로 정상인 데이터
특이도(Specificity) : (TN) / (TN + FP) : 불량으로 예측된 데이터 /  실제 불량인 데이터

p.75 밑의 F1-Measure 오타가 있습니다. 설명과 수식 모두 F1-Measure 로 수정되어야 합니다.

지적해주셔서 감사합니다.

**Comment by joonheepy** [comment]
빠른 정정 감사드립니다. 
학습하는 사람 입장에서 기본 개념에 오타가 있으면 이해하기까지 시간 낭비가 길어지는 만큼 오타 정정은 중요한 작업입니다. 
출판사가 너무 성급하게 책을 출시한게 아닌가 싶네요. 
보통 일본이나 영미권 책들은 오타가 적은데 유달리 한국 책들만 오타가 넘칩니다. ㅠㅠ 
(즉, 이 책만 오타가 많다는 것은 아닙니다. 다른 책들도 마찬가지로 오타가 많아요..ㅠ)
그래도 다른 책들에 비해 좋은 내용으로 알차게 구성해주셔서 공부에 많은 도움이 되고는 있습니다. 
감사합니다. 화이팅!
