### ISSUE TITLE
PART02 (p59~60) 코드 내용 제보

### ISSUE THREAD

**Issue by HeeKyung-Park** [Justin-A/DeepLearning101#8]
안녕하세요. 
다른 책과는 다르게 자세하고 어려운 주제도 다루어 주셔서, 책 잘 읽고있습니다. 

아래와 같이 코드 설명 중 잘못된 부분이 있어서 글 남깁니다.
p59~60에 보면,  (4), (5) 코드 설명이 잘못 매칭된 것 같습니다.

**Comment by Justin-A** [comment]
안녕하세요, Justin입니다.
지적해주신 내용을 책을 통해 확인해보았을 때, 올바르게 매칭된 것 같습니다. 
구체적으로 언급해주신다면 확인 후 답변드리도록 하겠습니다.

또한, 책 내 오타가 많으며 issues 게시판 내 closed 된 이슈들을 살펴보시면 오탈자에 대한 질문과 답변이 기록되어있습니다. 
책에 오타가 많아 책을 읽기에 불편한 점 죄송합니다.

감사합니다.
