### ISSUE TITLE
run 에러

### ISSUE THREAD

**Issue by karlie38** [Justin-A/DeepLearning101#9]
5-2_model_imbd_scratch 코드 에러가 납니다.

`
# Check batch data
sample_for_check = next(iter(train_iterator))
print(sample_for_check)
print(sample_for_check.text)
print(sample_for_check.label)`

여기서 keyError가 발생하고, 연달아 뒤에 모델 학습하는 부분에서도 keyError가 발생합니다.

확인 부탁드려도 될까요?

**Comment by Justin-A** [comment]
@8a496b 확인 후 답변 드리도록 하겠습니다.

**Comment by 8a496b** [comment]
@karlie38 (cc. @Justin-A )
제보 감사합니다! 말씀해주신 내용 오늘 저녁에 확인 해보겠습니다.

**Comment by 8a496b** [comment]
@karlie38 (cc. @Justin-A )

확인 결과, torchtext의 버전 문제가 있는 것 같습니다. 
제가 테스트한 환경은 google colab 환경인 (torch 1.7.0, torchtext 0.3.1) 을 기준이었습니다. (다시 확인한 결과, 해당 환경에서는 모두 정상 작동합니다) 지금 torchtext의 최신 버전은 0.8.1으로 확인되는데 버전 호환에 문제가 있는 것 같습니다. 

torchtext 최신 버전으로 변경하기 위해서는 다른 코드도 모두 변경해야할 것 같아서 수정하는데 시간이 필요할 것으로 보입니다.
혹시라도 급하게 사용해야 하는 상황이시면 `pip install torchtext==0.3.1`코드를 통해 torchtext를 다운그레이드하여 사용해주시기 바랍니다!
제보해주신 점 다시 한 번 감사드립니다 :)
